name: online-retarget
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch
  - pytorch-cuda=12.1
  - pyyaml
  - tqdm
  - pip:
      - hydra-core>=1.3
      - wandb
      - -e .[dev]
